
import type { ApiData } from './types';

export const TABLE_HEADERS: string[] = [
  "Model Name", "Provider", "Access link", "Popularity", "API", "Category", "Model Names",
  "Authentication Needed?", "Free Tier / Trial / Paid", "Pricing", "Rate Limits",
  "NSFW Restriction", "Latency", "Supported Formats", "Known Limitations / Weaknesses", "Notes / Comments"
];

export const IMAGE_MODELS_DATA: ApiData[] = [
  {
    modelName: "gemini-2.5-flash-image-preview",
    provider: "Google",
    accessLink: "Gemini API,(https://aistudio.google.com/models/gemini-2-5-flash-image), Vertex AI",
    popularity: "High (Viral as \"Nano Banana\")",
    api: "Yes",
    category: "Image",
    modelNames: "gemini-2.5-flash-image-preview",
    authentication: "API Key",
    tier: "Free Tier & Paid",
    pricing: "Paid: $0.039 per image ($30/1M output tokens). Free for limited testing in AI Studio.",
    rateLimits: "Paid: 2,000 RPM, 1.5M TPM. Free Tier: 500 RPM, 500k TPM.",
    nsfwRestriction: "Yes, configurable safety settings. Filters reportedly stricter.",
    latency: "Fast (\"rapid\").",
    supportedFormats: "Input: PNG, JPEG, WEBP. Output: PNG, JPEG, WEBP.",
    limitations: "Reports of quality drop (to 1024x1024) and stricter filters. Poor at style transfers.",
    notes: "Available via OpenRouter and fal.ai. Includes SynthID watermark."
  },
  {
    modelName: "Seedream 4.0",
    provider: "ByteDance",
    accessLink: "VolcEngine",
    popularity: "High (tops image editing leaderboards)",
    api: "Yes",
    category: "Image",
    modelNames: "Seedream 4.0",
    authentication: "API Key",
    tier: "Free Trial / Paid",
    pricing: "~$0.0175 to $0.03 per image depending on provider.",
    rateLimits: "Varies by provider (e.g., 10 RPM on BytePlus basic).",
    nsfwRestriction: "Not specified, assumed standard restrictions.",
    latency: "Very Fast (1.8s for 2K).",
    supportedFormats: "Input: JPEG, PNG. Output: up to 4K.",
    limitations: "Lacks multimodal reasoning compared to Gemini. Some outputs resemble upscaled 1K.",
    notes: "Available via BytePlus, Kie.ai, CometAPI, Fal.ai, Replicate. Excels at resolution and speed."
  },
  {
    modelName: "gpt-image-1",
    provider: "OpenAI",
    accessLink: "OpenAI API",
    popularity: "High",
    api: "Yes",
    category: "Image",
    modelNames: "gpt-image-1",
    authentication: "API Key",
    tier: "Paid Only (Tier 1+ required)",
    pricing: "Text Input: $5/1M tokens. Image Input: $10/1M tokens. Image Output: $40/1M tokens (~$0.02–$0.19 per image).",
    rateLimits: "Tiered by spending. Tier 1: 100k TPM.",
    nsfwRestriction: "Yes, OpenAI safety policies apply.",
    latency: "Slow (30–60s).",
    supportedFormats: "Input: PNG, JPEG, WEBP, GIF (non-animated). Output: PNG, JPEG, WEBP.",
    limitations: "High latency. API behind ChatGPT UI capabilities.",
    notes: "Multimodal with strong reasoning. Free tier excludes API."
  },
  {
    modelName: "imagen-4.0-ultra-generate-001",
    provider: "Google",
    accessLink: "Vertex AI,(https://replicate.com/google/imagen-4-ultra)",
    popularity: "High",
    api: "Yes",
    category: "Image",
    modelNames: "imagen-4.0-ultra-generate-001",
    authentication: "API Key",
    tier: "Free Tier / Trial / Paid",
    pricing: "$0.06 per output image.",
    rateLimits: "Paid: 10 RPM. Free: 5 RPM.",
    nsfwRestriction: "Yes, configurable safety settings.",
    latency: "~8.9s (Replicate).",
    supportedFormats: "Output: JPG, PNG. Up to 2K+.",
    limitations: "Input limited to 480 tokens.",
    notes: "Google's highest quality for photorealism. Includes SynthID watermark."
  },
  {
    modelName: "FLUX 1.1 Pro Ultra",
    provider: "Black Forest Labs",
    accessLink: "(https://docs.bfl.ai/quick_start/pricing), Fal.ai,(https://www.segmind.com/models/flux-1.1-pro-ultra/api)",
    popularity: "Moderate",
    api: "Yes",
    category: "Image",
    modelNames: "FLUX 1.1 Pro Ultra",
    authentication: "API Key",
    tier: "Free Trial / Paid",
    pricing: "$0.06 per image (BFL, Fal.ai).",
    rateLimits: "Varies. Together.ai Tier 1: 240 img/min.",
    nsfwRestriction: "Safety tolerance configurable (1–6).",
    latency: "Fast (8–10s).",
    supportedFormats: "Output: PNG, JPG. Up to 4MP.",
    limitations: "Struggles with abstract prompts. Lacks naturalism.",
    notes: "\"Raw\" mode for natural look. 2.5x faster than peers."
  },
  {
    modelName: "FLUX.1 Kontext Max",
    provider: "Black Forest Labs",
    accessLink: "(https://docs.bfl.ai/quick_start/pricing), Fal.ai, ComfyUI",
    popularity: "Moderate",
    api: "Yes",
    category: "Image",
    modelNames: "FLUX.1 Kontext Max",
    authentication: "API Key",
    tier: "Free Trial / Paid",
    pricing: "$0.08 per image (BFL, Fal.ai, ComfyUI).",
    rateLimits: "Varies.",
    nsfwRestriction: "Safety tolerance configurable.",
    latency: "Fast, optimized.",
    supportedFormats: "Input: JPEG, PNG, WEBP. Output: JPEG, PNG.",
    limitations: "Sometimes edits more than intended.",
    notes: "Premium model for typography and prompt adherence."
  },
  {
    modelName: "FLUX.1 Kontext Pro",
    provider: "Black Forest Labs",
    accessLink: "(https://docs.bfl.ai/quick_start/pricing), Fal.ai, Clarifai",
    popularity: "Moderate",
    api: "Yes",
    category: "Image",
    modelNames: "FLUX.1 Kontext Pro",
    authentication: "API Key",
    tier: "Free Trial / Paid",
    pricing: "$0.04 per image (BFL, ComfyUI). $0.02/request (Clarifai).",
    rateLimits: "Varies. Together.ai: 57 img/min.",
    nsfwRestriction: "Safety tolerance configurable.",
    latency: "Very Fast. Up to 8x faster than diffusion peers.",
    supportedFormats: "Input: JPEG, PNG, WEBP. Output: JPEG, PNG.",
    limitations: "Quality degrades in long edit chains (5+). Prompting can be tricky.",
    notes: "Flagship for fast, iterative text-guided editing."
  },
  {
    modelName: "Gemini 2.0 Flash Image Generation",
    provider: "Google",
    accessLink: "(https://developers.googleblog.com/en/experiment-with-gemini-20-flash-native-image-generation/)",
    popularity: "Low",
    api: "Yes (Experimental)",
    category: "Image",
    modelNames: "Gemini 2.0 Flash Image Generation",
    authentication: "API Key",
    tier: "Experimental",
    pricing: "Not specified (likely replaced by 2.5).",
    rateLimits: "2,000 RPM, 3M TPM.",
    nsfwRestriction: "Yes, Google safety policies.",
    latency: "Fast.",
    supportedFormats: "Not specified.",
    limitations: "Experimental, lacks 2.5 features. Better at style transfers vs 2.5.",
    notes: "Precursor to Gemini 2.5 Flash."
  }
];

export const REASONING_MODELS_DATA: ApiData[] = [
  {
    modelName: "GPT-5",
    provider: "OpenAI",
    accessLink: "(https://platform.openai.com/docs/models/gpt-5)",
    popularity: "1 (SOTA on multiple benchmarks)",
    api: "Responses API, Chat Completions API",
    category: "Chat",
    modelNames: "gpt-5, gpt-5-2025-08-07",
    authentication: "API key",
    tier: "Paid",
    pricing: "Input: $1.25/1M tokens; Output: $10.00/1M tokens",
    rateLimits: "Tier-based; Tier 1: 500 RPM, 500k TPM. Tier 5: 15,000 RPM, 40M TPM",
    nsfwRestriction: "Subject to OpenAI Usage Policies",
    latency: "Medium",
    supportedFormats: "Text, Image",
    limitations: "High cost compared to smaller models. Reasoning effort parameter (low, medium, high) affects cost and performance.",
    notes: "Best-in-class model for coding and agentic tasks. Features a \"thinking\" mode that uses internal reasoning tokens, which are billed as output."
  },
  {
    modelName: "Gemini 2.5 Pro",
    provider: "Google",
    accessLink: "(https://cloud.google.com/vertex-ai/generative-ai/docs/models/gemini/2-5-pro)",
    popularity: "2 (Top performer on vision and tutoring benchmarks)",
    api: "Vertex AI API, Google AI Studio",
    category: "Chat",
    modelNames: "gemini-2.5-pro, gemini-2.5-pro-preview-06-05",
    authentication: "API key, Application Default Credentials",
    tier: "Paid, with Free Trial ($300 credits for new customers)",
    pricing: "Standard: $7/1M input, $21/1M output (text). Long Context (>200k): $14/1M input, $42/1M output (text)",
    rateLimits: "Default: 90,000 RPM. Experimental versions have a 10 QPM limit.",
    nsfwRestriction: "Configurable content filters for harm categories (Hate Speech, Harassment, etc.).",
    latency: "P50 < 3.2s, P95 < 6.8s (us-central1)",
    supportedFormats: "Text, Code, Image, Video, Audio, PDF, Function Calling",
    limitations: "Does not support image generation. Compositional function calling is only available in Google AI Studio.",
    notes: "Features \"Deep Think\" enhanced reasoning mode. Possesses a 1M token context window and excels at multimodal understanding."
  },
  {
    modelName: "Claude 4 Opus",
    provider: "Anthropic",
    accessLink: "(https://console.anthropic.com)",
    popularity: "3 (Top performer on coding and honesty benchmarks)",
    api: "Messages API",
    category: "Chat",
    modelNames: "claude-opus-4-1-20250805, claude-4-opus",
    authentication: "API key",
    tier: "Paid",
    pricing: "Input: $15/1M tokens; Output: $75/1M tokens",
    rateLimits: "Custom limits based on plan and spend. Weekly limits for subscription users; API users have spend-based limits.",
    nsfwRestriction: "Governed by Anthropic's Usage Policy; model shows a 98.76% harmless response rate to violative requests.",
    latency: "Hybrid reasoning allows for instant or extended thinking; latency varies with \"thinking budget\".",
    supportedFormats: "JSON (requests/responses)",
    limitations: "Highest price point in the market. Latency can be higher in extended thinking mode. Recent service issues reported.",
    notes: "A hybrid reasoning model with a 200K context window, positioned for mission-critical tasks where accuracy outweighs cost and speed."
  },
  {
    modelName: "Grok 4",
    provider: "xAI",
    accessLink: "(https://x.ai/api)",
    popularity: "4 (Top performer in search-related tasks)",
    api: "OpenAI/Anthropic Compatible API",
    category: "Chat",
    modelNames: "grok-4, grok-4-0709, grok-4-fast-reasoning",
    authentication: "API key (requires X Premium subscription)",
    tier: "Paid (base access included with X Premium/Premium+)",
    pricing: "grok-4-0709: $3/1M input, $15/1M output. grok-4-fast: $0.20/1M input, $0.50/1M output",
    rateLimits: "grok-4-0709: 2M TPM, 480 RPM. grok-4-fast: 4M TPM, 480 RPM",
    nsfwRestriction: "Permissive; \"Spicy\" mode allows nudity and sexualized themes in image generation, but prohibits deepfakes of real individuals.",
    latency: "\"Lightning fast\" for grok-4-fast model.",
    supportedFormats: "Text, Image (Input); Text, Image (Output)",
    limitations: "Knowledge cutoff is Nov 2024; requires Live Search tool for current events. Does not support reasoning_effort parameter.",
    notes: "Differentiated by real-time search integration with X. grok-4-fast model offers a 2M token context window and SOTA price-to-intelligence ratio."
  },
  {
    modelName: "OpenAI o3",
    provider: "OpenAI",
    accessLink: "(https://platform.openai.com/docs/models)",
    popularity: "5 (High performer on complex reasoning)",
    api: "Responses API, Chat Completions API",
    category: "Chat",
    modelNames: "o3, o3-2025-04-16",
    authentication: "API key",
    tier: "Paid",
    pricing: "Input: $2/1M tokens; Output: $8/1M tokens",
    rateLimits: "Default: 1M TPM, 1k RPM. Enterprise: 10M TPM, 10k RPM",
    nsfwRestriction: "Subject to OpenAI Usage Policies",
    latency: "Medium; reasoning effort affects latency.",
    supportedFormats: "Text, Image",
    limitations: "Does not support visual reasoning in the o3-mini version. Using max_completion_tokens can truncate reasoning and result in no visible output.",
    notes: "Predecessor to GPT-5, excels at STEM applications and multi-step problems. Uses reasoning tokens that add to output cost."
  },
  {
    modelName: "DeepSeek V3 / R1",
    provider: "DeepSeek AI",
    accessLink: "(https://api.deepseek.com)",
    popularity: "6 (Strong open-weight competitor)",
    api: "OpenAI Compatible API",
    category: "Chat",
    modelNames: "deepseek-chat (V3.1 non-thinking), deepseek-reasoner (R1/V3.1 thinking)",
    authentication: "API key",
    tier: "Paid (Pay-as-you-go with potential \"granted balance\")",
    pricing: "Input: $0.56/1M tokens; Output: $1.68/1M tokens (Cache hits are cheaper)",
    rateLimits: "No hard RPM/TPM limits, but requests may be slowed during high traffic. Connections time out after 30 minutes.",
    nsfwRestriction: "Highly unrestricted; known to generate content that other models refuse, including simulated misaligned AGI strategies.",
    latency: "Variable; depends on server load.",
    supportedFormats: "JSON (requests/responses); supports JSON output mode.",
    limitations: "deepseek-reasoner does not support function calling or parameters like temperature and top_p. CoT content must be removed for multi-turn conversations.",
    notes: "Strong open-weight MoE model (671B params). deepseek-reasoner explicitly outputs its Chain of Thought (CoT), which is billed."
  },
  {
    modelName: "Llama 3.1 405B",
    provider: "Meta / Cloud Providers",
    accessLink: "(https://cloud.google.com/vertex-ai/generative-ai/docs/partner-models/llama)",
    popularity: "7 (Top-tier open-weight model)",
    api: "Various (Vertex AI, Hugging Face, etc.)",
    category: "Chat",
    modelNames: "llama-3.1-405b-instruct-maas, Meta-Llama-3.1-405B-Instruct",
    authentication: "API key (via provider)",
    tier: "Paid (Pay-as-you-go on Vertex AI)",
    pricing: "Varies by provider. Some offer free access for a limited time (e.g., SambaNova).",
    rateLimits: "On Vertex AI: 60 QPM",
    nsfwRestriction: "Governed by Llama 3.1 Community License and Acceptable Use Policy.",
    latency: "Varies by hosting provider.",
    supportedFormats: "Text, Code",
    limitations: "Requires significant hardware for self-hosting (at least 400GiB of GPU VRAM for FP8 version). Knowledge cutoff is Dec 2023.",
    notes: "State-of-the-art open-weight model, competitive with proprietary leaders on benchmarks like MMLU and MATH. Available via multiple cloud and specialized hosting partners."
  },
  {
    modelName: "Mistral Large 2",
    provider: "Mistral AI",
    accessLink: "(https://console.mistral.ai)",
    popularity: "8 (Strong multilingual and coding performance)",
    api: "La Plateforme API",
    category: "Chat",
    modelNames: "mistral-large-2407, mistral-large-latest",
    authentication: "API key",
    tier: "Paid, with Free tier for trial",
    pricing: "Input: $0.002/1k tokens; Output: $0.006/1k tokens ($2/$6 per 1M)",
    rateLimits: "Tier-based (RPS, TPM, Tokens/month). Upgrades based on total billed amount.",
    nsfwRestriction: "Mistral Moderation service available to detect harmful content.",
    latency: "High throughput on single-node inference.",
    supportedFormats: "JSON (requests/responses)",
    limitations: "Training focused on reducing hallucinations and providing succinct answers, which may differ from other models optimized for verbosity.",
    notes: "Flagship model with 128k context window and strong multilingual support. Features advanced function calling for complex applications."
  },
  {
    modelName: "Qwen2.5-Max",
    provider: "Alibaba Cloud",
    accessLink: "(https://www.alibabacloud.com/help/en/model-studio/)",
    popularity: "9 (Leading model from China, strong multilingual)",
    api: "DashScope API (OpenAI Compatible)",
    category: "Chat",
    modelNames: "qwen-max-2025-01-25, qwen-max",
    authentication: "API key",
    tier: "Paid, with Free Quota (1M input/1M output tokens for 180 days)",
    pricing: "Input: $1.6/1M tokens; Output: $6.4/1M tokens",
    rateLimits: "qwen3-max: 600 RPM, 1M TPM.",
    nsfwRestriction: "Subject to Alibaba Cloud policies.",
    latency: "Not specified.",
    supportedFormats: "Text, Image, Video (multimodal understanding)",
    limitations: "qwen-max does not support the \"deep thinking\" mode available in qwen-plus.",
    notes: "Best-performing model in the Qwen series, competitive with other SOTA models on benchmarks like Arena-Hard and LiveCodeBench."
  },
  {
    modelName: "Cohere Command R+",
    provider: "Cohere",
    accessLink: "(https://docs.cohere.com/docs/command-r-plus)",
    popularity: "10 (Strong in RAG and tool use)",
    api: "Chat API",
    category: "Chat",
    modelNames: "command-r-plus, command-r-plus-08-2024",
    authentication: "API key",
    tier: "Paid, with Trial key (limited to 1,000 calls/month)",
    pricing: "Input: $2.5/1M tokens; Output: $10/1M tokens",
    rateLimits: "Trial: 20 RPM. Production: 500 RPM.",
    nsfwRestriction: "Built-in protections against core harms. \"Strict\" and \"Contextual\" safety modes available; cannot be disabled.",
    latency: "Aug 2024 release has ~25% lower latency than previous version.",
    supportedFormats: "JSON (requests/responses)",
    limitations: "Primarily excels in 10 key business languages; performance may be lower in others. Can still generate toxic text despite safeguards.",
    notes: "Optimized for complex RAG and multi-step tool use (agents). 128k context window. Knowledge cutoff June 1, 2024."
  }
];

export const NON_REASONING_MODELS_DATA: ApiData[] = [
  {
    modelName: "GPT-4o & GPT-4o mini",
    provider: "OpenAI",
    accessLink: "(https://platform.openai.com)",
    popularity: "Very High",
    api: "REST, Python SDK, TypeScript SDK",
    category: "Chat, Image (Vision)",
    modelNames: "gpt-4o, gpt-4o-mini, gpt-4o-search-preview",
    authentication: "API key",
    tier: "Paid, with free credits for new developers ($18)",
    pricing: "GPT-4o: $2.50/M input, $10.00/M output. GPT-4o mini: $0.15/M input, $0.60/M output",
    rateLimits: "Tiered RPM/TPM based on usage. Tier 1 (Free) is low; scales with payment history. GPT-4o has 5x higher limits than GPT-4 Turbo",
    nsfwRestriction: "Policy prohibits sexually explicit content, but is exploring allowing erotica/gore in age-appropriate API contexts. A shift from a stricter past policy",
    latency: "GPT-4o: Low to Medium. Avg. audio response ~320ms. Throughput ~109 tokens/sec. GPT-4o mini is faster",
    supportedFormats: "Text, Image (URL, base64), JSON (Structured Outputs), Audio (via separate APIs)",
    limitations: "Can be slower and more expensive than competitors for certain tasks. Some benchmarks show it struggles with reasoning tasks compared to older GPT-4 versions",
    notes: "Flagship model with a massive ecosystem and strong tool integration. Best for general reasoning and multi-modal tasks. OpenAI is deprecating older models to push users to the latest versions"
  },
  {
    modelName: "Gemini 2.5 Flash",
    provider: "Google",
    accessLink: "(https://ai.google.dev)",
    popularity: "High",
    api: "REST, Python, JS, Go, Java, Swift, Android SDKs",
    category: "Chat, Image (Vision), Audio, Video",
    modelNames: "gemini-2.5-flash, gemini-2.5-flash-lite",
    authentication: "API key",
    tier: "Free Tier (via AI Studio) & Paid Tier. Free tier has generous limits (e.g., 1M tokens/min for Flash)",
    pricing: "2.5 Flash: $0.30/M input, $2.50/M output",
    rateLimits: "Tiered RPM/TPM/RPD based on billing status and spend.",
    nsfwRestriction: "Strict Prohibited Use Policy. Bans sexually explicit content, hate speech, harassment, and other harmful activities. Exceptions for educational/scientific/artistic purposes",
    latency: "2.5 Flash is optimized for low-latency and high-volume tasks",
    supportedFormats: "Text, Image (PNG, JPEG, WEBP), Audio (MP3, WAV, FLAC), Video (MP4, MOV, AVI), PDF, plain text",
    limitations: "Developer ecosystem and tooling are still maturing compared to OpenAI. High latency on large prompts is a significant issue for real-time applications",
    notes: "Leads the market with a massive 1M+ token context window. Deep integration with Google Cloud (Vertex AI)"
  },
  {
    modelName: "Claude 3.5 Sonnet",
    provider: "Anthropic",
    accessLink: "(https://docs.anthropic.com)",
    popularity: "High",
    api: "REST, Python SDK",
    category: "Chat, Image (Vision)",
    modelNames: "claude-3.5-sonnet-20240620, claude-3-sonnet-20240229",
    authentication: "API key",
    tier: "Paid, with some free credits/hours possible. Also available via AWS Bedrock and Google Vertex AI",
    pricing: "$3.00/M input, $15.00/M output. Prompt caching can reduce costs up to 90%",
    rateLimits: "Tiered RPM/TPM/TPD. Tiers scale with account status and spend. Cache-aware limits do not count cached tokens against ITPM",
    nsfwRestriction: "Prohibits illegal/harmful content. Consumer data may be used for training (opt-out available), but business/API data is not used for training",
    latency: "Medium. Slower TTFT (0.64s) than Haiku (0.36s) but comparable overall generation time. Slower than GPT-4o on average",
    supportedFormats: "Text, Image, PDF, JSON (Tool Use)",
    limitations: "Can be prone to overzealous refusals and hallucinations on complex coding tasks. Output length is limited",
    notes: "Excellent balance of performance, speed, and cost. Strong in coding (HumanEval 93.7%) and graduate-level reasoning. Known for strong safety guardrails and enterprise focus"
  },
  {
    modelName: "Mistral Large 2",
    provider: "Mistral AI",
    accessLink: "(https://docs.mistral.ai)",
    popularity: "Medium-High",
    api: "REST, Python, TypeScript SDKs",
    category: "Chat",
    modelNames: "mistral-large-2411, mistral-large-latest",
    authentication: "API key",
    tier: "Free tier for prototyping, then pay-as-you-go",
    pricing: "$2.00/M input, $6.00/M output",
    rateLimits: "Tiered RPS/TPM/TPM (monthly) based on total billed amount. Tiers are automatically upgraded with spend",
    nsfwRestriction: "Permissive for legal content. Moderation API available to classify harmful content. Research license for open-weight models prohibits commercial use",
    latency: "Medium. Slower TTFT and throughput than GPT-4o or Claude 3.5 Sonnet. Latency can be higher for longer queries",
    supportedFormats: "Text, JSON (Tool Use)",
    limitations: "Less mature ecosystem than OpenAI. Open-weight models require significant hardware to self-host. Performance can lag top-tier models in some reasoning benchmarks",
    notes: "Top-tier European model with exceptional native multilingual capabilities. Offers both premier proprietary APIs and powerful open-weight models"
  },
  {
    modelName: "Llama 3.1 (405B, 70B, 8B)",
    provider: "Meta",
    accessLink: "(https://llama.meta.com)",
    popularity: "Very High",
    api: "REST, Python, TypeScript SDKs (via Meta API or third parties)",
    category: "Chat, Image (Vision)",
    modelNames: "llama-3.1-405b-instruct, llama-3.1-70b-instruct, llama-3.1-8b-instruct",
    authentication: "API key (via providers)",
    tier: "Open-source (self-host). API access via providers like AWS, Google Cloud, Azure, Together AI, Groq, OpenRouter",
    pricing: "Varies by provider. E.g., Llama 3.1 70B on DeepInfra is $0.40/M tokens. Llama 4 Maverick (successor) estimated at $0.19-$0.49/M tokens",
    rateLimits: "Varies by provider. Meta's own preview API has 3,000 RPM / 1M TPM. Groq offers 30 RPM / 12k TPM for 70B",
    nsfwRestriction: "Permissive Llama 3.1 Community License. Acceptable Use Policy prohibits illegal activities, harm, and deception. Data sent to Meta's API is not used for training",
    latency: "Varies by provider and model size. Groq offers extremely low latency. 405B model has high latency due to size. Llama 3.1 is slower than Llama 3",
    supportedFormats: "Text, Image (via multimodal models)",
    limitations: "405B model requires massive hardware (e.g., 6-10 A100 GPUs) to run, making it impractical for most to self-host. Long context performance can degrade near its 128k limit",
    notes: "Cornerstone of the open-source movement. Offers near SOTA performance with maximum flexibility. Can be self-hosted for privacy or accessed via numerous cloud and API providers"
  },
  {
    modelName: "DeepSeek-V2 / V3",
    provider: "DeepSeek AI",
    accessLink: "(https://platform.deepseek.com)",
    popularity: "Medium-High",
    api: "REST (OpenAI compatible)",
    category: "Chat",
    modelNames: "deepseek-chat, deepseek-reasoner (V2), deepseek-v3",
    authentication: "API key",
    tier: "Paid, with free credits/trial sometimes available",
    pricing: "V2 Chat: $0.27/M input, $1.10/M output. V3 (R1) pricing updated to $0.56/M input, $1.68/M output",
    rateLimits: "No explicit rate limits. Requests are queued during high traffic, leading to increased latency instead of 429 errors. Connections time out after 30 minutes",
    nsfwRestriction: "Prohibits illegal/harmful content. Terms state data may be used to improve services. Does not process sensitive personal data",
    latency: "High. Can be significantly slower than competitors, especially during peak times due to the queuing system. Basic tasks can take 4-6 seconds",
    supportedFormats: "Text, JSON",
    limitations: "Latency is a major weakness due to the lack of hard rate limits. Performance can be inconsistent. Smaller ecosystem and less documentation than major players",
    notes: "A market disruptor with performance competitive with top models, especially in coding and math, at a fraction of the cost. The \"no rate limit\" policy is unique"
  },
  {
    modelName: "Command R+",
    provider: "Cohere",
    accessLink: "(https://docs.cohere.com)",
    popularity: "Medium",
    api: "REST, Python SDK",
    category: "Chat",
    modelNames: "command-r-plus, command-r-plus-08-2024",
    authentication: "API key",
    tier: "Trial key (free, 1000 calls/month, low RPM) & Production key (paid)",
    pricing: "$2.50/M input, $10.00/M output",
    rateLimits: "Production key: 500 RPM for Chat endpoint. Trial key is very limited (20 RPM)",
    nsfwRestriction: "Usage policy prohibits illegal/harmful content. Data from enterprise customers is not used for training. Data transits through US-based servers",
    latency: "Low TTFT (~0.22s). Overall throughput is slower than average (~35 tokens/sec)",
    supportedFormats: "Text, JSON (Tool Use), Documents (for RAG)",
    limitations: "Less tuned for open-ended creative chat compared to generalist models. Older versions have a smaller context window (16k)",
    notes: "Highly specialized for enterprise RAG and multi-step tool use. Excellent for building applications grounded in proprietary knowledge bases"
  },
  {
    modelName: "Grok-3 / Grok-4",
    provider: "xAI",
    accessLink: "(https://docs.x.ai)",
    popularity: "Medium",
    api: "REST (OpenAI & Anthropic compatible)",
    category: "Chat, Image (Vision)",
    modelNames: "grok-3, grok-3-fast, grok-4-0709",
    authentication: "API key",
    tier: "Public beta with $25 free monthly credits until end of 2024. Paid tiers after",
    pricing: "Grok-4: $3.00/M input, $15.00/M output. Grok-4 Fast: $0.20/M input, $0.50/M output (for <128k context)",
    rateLimits: "Tiered RPM/TPM. Grok-4 has 480 RPM / 2M TPM. Grok-3 has 600 RPM",
    nsfwRestriction: "AUP prohibits illegal activities, harm, and misleading uses. Enterprise data is not used for training and is deleted within 30 days",
    latency: "Grok-3 Fast is optimized for low latency. Grok-3 averages 67-90ms response time. Grok-4 is slower",
    supportedFormats: "Text, Image, JSON (Structured Outputs)",
    limitations: "Ecosystem is nascent. Consumer product message limits can be confusing and restrictive. API is still in public beta",
    notes: "Unique value is real-time knowledge from the X platform. \"Unhinged\" mode offers a distinct, less filtered personality. Strong reasoning and coding capabilities"
  },
  {
    modelName: "Nemotron-4 340B",
    provider: "NVIDIA",
    accessLink: "(https://build.nvidia.com)",
    popularity: "Low-Medium",
    api: "REST (OpenAI compatible, via providers like DeepInfra, OpenRouter)",
    category: "Chat",
    modelNames: "nvidia/nemotron-4-340b-instruct",
    authentication: "API key (via providers)",
    tier: "Open-source (NVIDIA Open Model License). API access via third parties is typically paid",
    pricing: "Varies by provider. Not widely available as a pay-as-you-go API yet. High self-hosting costs ($240k+ hardware)",
    rateLimits: "Not specified by NVIDIA; depends on the third-party API provider",
    nsfwRestriction: "Permissive open license allows commercial use. Prohibits illegal/harmful content. Model may amplify biases from training data",
    latency: "High latency due to model size. Primarily for non-real-time tasks. Optimized for throughput on NVIDIA hardware",
    supportedFormats: "Text",
    limitations: "Very short context window (4,096 tokens). Extremely high hardware requirements for self-hosting. Not suitable for conversational or long-document tasks",
    notes: "A massive, powerful open model primarily designed for generating high-quality synthetic data to train other models. Best suited for research and large-scale, specialized enterprise use"
  },
  {
    modelName: "Qwen2.5 Series",
    provider: "Alibaba Cloud",
    accessLink: "(https://alibabacloud.com/en/model-studio)",
    popularity: "Low-Medium",
    api: "REST (OpenAI compatible), Python SDK",
    category: "Chat, Image (Vision), Audio, Video",
    modelNames: "qwen-max, qwen-plus, qwen2.5-coder-32b-instruct",
    authentication: "API key",
    tier: "Free quota (1M tokens for 180 days) for new Model Studio users. Some smaller models are free",
    pricing: "Qwen-Max: $1.60/M input, $6.40/M output. Qwen-Plus: $0.40/M input, $1.20/M output. Coder models are cheaper",
    rateLimits: "RPM/TPM limits vary by model. Qwen-Max is 60 RPM / 100k TPM. Open-source models on the platform have higher limits (600 RPM / 1M TPM)",
    nsfwRestriction: "AUP prohibits illegal/harmful use. Data collected is used to provide and improve services. Not intended for minors",
    latency: "High latency reported for multimodal (Omni) models, especially for audio generation (>20s). Text models are more responsive",
    supportedFormats: "Text, Image, Audio, Video, JSON (Tool Use)",
    limitations: "Context window on some commercial models (Qwen2.5-Max) is smaller (8k-32k) than open-source competitors. Ecosystem is less mature outside of the APAC region",
    notes: "Leading model family from the Chinese market with strong multilingual and coding capabilities. Offers both proprietary commercial models and a wide range of open-source versions"
  }
];

export const VIDEO_MODELS_DATA: ApiData[] = [
  {
    modelName: "Veo 3",
    provider: "Google",
    accessLink: "Vertex AI",
    popularity: "High",
    api: "REST",
    category: "Video",
    modelNames: "veo-3.0-generate-001, veo-3.0-fast-generate-001, veo-3.0-generate-preview",
    authentication: "API key (via Google Cloud)",
    tier: "Trial / Paid",
    pricing: "Paid: ~$0.75/second for video + audio output via API. Also available via Google AI Ultra subscription ($249.99/mo).",
    rateLimits: "Low: 4 RPM / 50 RPD for Veo 3; 10 RPM for veo-3.0-generate-preview.",
    nsfwRestriction: "Strict. Prohibited use policy blocks harmful/explicit content. personGeneration parameter allows disallowing people/faces.",
    latency: "Medium-High: 3-5 minutes per generation.",
    supportedFormats: "Input: Text, Image (JPEG, PNG). Output: Video (MP4).",
    limitations: "Inconsistent lip-sync, erroneous auto-subtitles, very low daily generation limits, and high API cost can hinder iterative development.",
    notes: "Standout feature is native audio and lip-sync generation, a major advantage over competitors requiring separate audio workflows."
  },
  {
    modelName: "Runway Gen-4",
    provider: "Runway",
    accessLink: "(https://runwayml.com/api)",
    popularity: "High",
    api: "REST",
    category: "Video",
    modelNames: "Gen-3 Alpha, Gen-4, Gen-4 Turbo, Aleph",
    authentication: "API key",
    tier: "Free Tier / Paid",
    pricing: "Paid: Credit-based. API credits are separate from web app subscription. Gen-4 is 12 credits/sec; Gen-4 Turbo is 5 credits/sec.",
    rateLimits: "Tiered: Higher spending unlocks higher concurrency (1-20) and daily generation limits (50-25,000).",
    nsfwRestriction: "Strict. Prohibits sexually explicit content, nudity, graphic violence, hateful conduct, and CSAM. Moderated generations still consume credits.",
    latency: "Low-Medium: Faster than many competitors, especially with Turbo models. Can be ~10 seconds for a 10s video.",
    supportedFormats: "Input: Image (JPEG, PNG, WebP), Video (MP4, MOV, WebM). Output: Video (MP4).",
    limitations: "Gen-4 is image-to-video only, requiring a source image. No native audio generation. Steep learning curve for advanced features.",
    notes: "Positioned as a professional creative toolkit with extensive control features like Director Mode and Motion Brush for filmmakers."
  },
  {
    modelName: "Kling AI",
    provider: "Kuaishou",
    accessLink: "Kling AI API",
    popularity: "High",
    api: "REST",
    category: "Video",
    modelNames: "Kling 1.6, Kling 2.1, Kling 2.5 Turbo",
    authentication: "API key",
    tier: "Free Tier / Paid",
    pricing: "Paid: Credit-based subscriptions (e.g., $10/mo for 660 credits). Pay-as-you-go API access via third parties (~$0.16/5s video).",
    rateLimits: "Not explicitly detailed, but performance is heavily tiered between free and paid users.",
    nsfwRestriction: "Strict. Built-in NSFW filter to prevent adult content generation. Policy prohibits explicit, illegal, or adult content.",
    latency: "High (Free Tier), Medium (Paid): Free tier can take minutes to hours. Paid plans are faster (3-8 minutes).",
    supportedFormats: "Input: Text, Image (JPG, PNG). Output: Video (MP4, MOV, WebM).",
    limitations: "No native audio generation. Free tier is extremely slow due to server demand. Struggles with some animation styles and complex movements.",
    notes: "Highly regarded for realistic physics simulation, prompt accuracy, and ability to generate longer videos (up to 2 minutes)."
  },
  {
    modelName: "Sora",
    provider: "OpenAI",
    accessLink: "Not Available",
    popularity: "Very High",
    api: "Not Available",
    category: "Video",
    modelNames: "Sora",
    authentication: "Not Applicable",
    tier: "Paid (Consumer)",
    pricing: "Paid: Access via consumer ChatGPT Plus ($20/mo). No public API or API pricing available.",
    rateLimits: "Not Applicable",
    nsfwRestriction: "Strict. Adheres to OpenAI's usage policies, prohibiting NSFW, hateful, and violent content.",
    latency: "Not Applicable",
    supportedFormats: "Not Applicable",
    limitations: "Primary limitation is the complete lack of a developer API. Consumer version quality can be inconsistent and lacks native audio.",
    notes: "Included due to market influence. Capable of generating long (60s), coherent, multi-shot videos. A public API is highly anticipated."
  },
  {
    modelName: "Synthesia",
    provider: "Synthesia",
    accessLink: "(https://docs.synthesia.io/)",
    popularity: "High",
    api: "REST",
    category: "Video (Avatar)",
    modelNames: "N/A (Platform)",
    authentication: "API key",
    tier: "Free Tier / Paid",
    pricing: "Paid: Subscription-based (minutes/month). API access starts with Creator plan ($89/mo for 30 min).",
    rateLimits: "Tiered: Creator plan has 60 req/min (read). Enterprise plans up to 120 req/min.",
    nsfwRestriction: "Strict. Prohibits adult entertainment, harmful, and obscene content. Stock avatars have additional restrictions on sensitive topics (politics, religion).",
    latency: "Low-Medium: 3-5 minutes for video processing.",
    supportedFormats: "Input: Text, Script audio. Output: Video (MP4).",
    limitations: "Unsuitable for creative/artistic video. Avatars can lack emotional range. Key enterprise features (SCORM) are gated behind expensive custom plans.",
    notes: "Market leader for corporate communication and training videos, with a focus on realistic avatars and extensive language support."
  },
  {
    modelName: "HeyGen",
    provider: "HeyGen",
    accessLink: "HeyGen API",
    popularity: "Medium-High",
    api: "REST",
    category: "Video (Avatar)",
    modelNames: "N/A (Platform)",
    authentication: "API key",
    tier: "Free Tier / Paid",
    pricing: "Paid: Credit-based. 1 credit = 1 min video. Pro plan is $99/mo for 100 credits.",
    rateLimits: "Not explicitly detailed.",
    nsfwRestriction: "Assumed strict, in line with industry standards for avatar platforms.",
    latency: "Medium: Standard video generation times for avatar platforms.",
    supportedFormats: "Input: Text. Output: Video.",
    limitations: "Focus on avatars makes it unsuitable for cinematic generation. Credit system can be costly at scale.",
    notes: "Differentiates with interactive avatars for real-time conversation and a dedicated video translation API."
  },
  {
    modelName: "Dream Machine",
    provider: "Luma Labs",
    accessLink: "Luma API",
    popularity: "Medium-High",
    api: "REST",
    category: "Video",
    modelNames: "Ray2",
    authentication: "API key (Bearer JWT)",
    tier: "Free Tier / Paid",
    pricing: "Paid: Generation-based. Free tier offers 30 generations/mo. Standard plan is $29.99/mo for 120 generations.",
    rateLimits: "Build Tier: 10 concurrent generations, 20 create requests/min.",
    nsfwRestriction: "Strict. Prohibits NSFW, hateful imagery, graphic violence, and illegal activities.",
    latency: "Low (Paid), High (Free): Paid users get priority. Free tier can be queued for hours during peak times.",
    supportedFormats: "Input: Text, Image. Output: Video.",
    limitations: "Video length is limited to 5-10 seconds. Coherence can break down quickly. Free tier is unreliable due to long queue times.",
    notes: "Known for very fast generation speeds and excellent motion understanding, making it great for rapid prototyping."
  },
  {
    modelName: "Pika",
    provider: "Pika Labs",
    accessLink: "Pika API",
    popularity: "Medium-High",
    api: "REST",
    category: "Video",
    modelNames: "Pika 1.0, Pika 1.5, Pika 2.0, Pika 2.1, Pika 2.2",
    authentication: "API key (via partnership contact)",
    tier: "Free Tier / Paid",
    pricing: "Paid: Pay-as-you-go API. $0.05/sec (Pika 1.0) to $0.156/sec (Pika 2.0 with features).",
    rateLimits: "20 generations per minute for all users.",
    nsfwRestriction: "Strict. Prohibits NSFW, nudity, sexual content, violence, and gore. Violations can lead to a permanent ban.",
    latency: "Low: Designed for fast turnaround, with generations in seconds to minutes.",
    supportedFormats: "Input: Text, Image. Output: Video (MP4, 720p).",
    limitations: "API output limited to 720p. Short clip duration. Some users find it unsuitable for professional business applications.",
    notes: "Popular for social media content due to its unique stylized \"Pikaffects\" and creative features like Modify Region."
  },
  {
    modelName: "DeepBrain AI",
    provider: "DeepBrain AI",
    accessLink: "(https://docs.aistudios.com/aistudioV3/getting-started)",
    popularity: "Medium",
    api: "REST",
    category: "Video (Avatar)",
    modelNames: "N/A (Platform)",
    authentication: "API key (AppId, UserKey)",
    tier: "Trial / Paid",
    pricing: "Paid: Subscription-based (minutes/month). API access on Pro plan (~$225/mo for 90 min).",
    rateLimits: "Not explicitly detailed.",
    nsfwRestriction: "Assumed strict, in line with enterprise avatar platforms.",
    latency: "High: Video rendering can be slow (1-10 minutes or more), with a queue-based system that can take up to 36+ hours after priority quota is used.",
    supportedFormats: "Input: Text, URL, Document. Output: Video.",
    limitations: "Slow rendering times. Inability to preview videos before rendering is a major workflow issue. Final output can sometimes look unnatural.",
    notes: "All-in-one platform with integrated ChatGPT for scripting and real-time conversational avatars."
  },
  {
    modelName: "Stable Video Diffusion",
    provider: "Stability AI",
    accessLink: "(https://replicate.com/stability-ai/stable-diffusion)",
    popularity: "Medium",
    api: "REST",
    category: "Video",
    modelNames: "SVD, SVD XT",
    authentication: "API key",
    tier: "Free (Non-Commercial) / Paid",
    pricing: "Paid: Varies by host (e.g., Replicate is ~$0.0038/run). Free for non-commercial use or entities with <$1M revenue.",
    rateLimits: "Varies by hosting platform.",
    nsfwRestriction: "Permissive (self-hosted), Strict (hosted). Official policy prohibits sexually explicit content, but open-source nature allows disabling filters.",
    latency: "Low: Typically completes within seconds on platforms like Replicate.",
    supportedFormats: "Input: Image (RGB). Output: Video.",
    limitations: "Primarily an image-to-video model. Fragmented API access. Lacks advanced features of closed-source competitors. Official API was deprecated.",
    notes: "The leading open-source model, offering maximum flexibility and customization for developers who can manage their own infrastructure."
  }
];
